### ISSUE TITLE
Exceptions at the start of the game

### ISSUE THREAD

**Issue by RychuP** [Sofistico/MagiRogue#35]
I honestly don't have any luck with your game. A few months ago when I tried to run it, I couldn't get to the gameplay neither. Please try to keep your master branch in the playable state at all times otherwise it just puts off any potential contributors.

1. After pressing Start Game, creating a Wizard and pressing Begin!:

![screenshot](https://i.ibb.co/xKZVHmv/startgameexception.png)

2. After pressing Test Map in the main menu:

![screenshot](https://i.ibb.co/Hrm7hB3/testmapexception.png)

**Comment by Sofistico** [comment]
True!
I'm quite sorry about it, my master branch is quite borked right now.... I won't be able to fix all issues right now, but give me just a few more months and you will be able to at the very least start the game!

**Comment by Sofistico** [comment]
This specific issue is already fixed in my latest feature branch, but that branch will take a while to be merged, since it's still in the process of being developed

**Comment by Sofistico** [comment]
But for some months yet, please consider the game broken, unplayable and probably ugly. Not specifically in that order!

**Comment by Sofistico** [comment]
And thank you for your interest in this game of mine!

**Comment by Sofistico** [comment]
Fixed by #39
